library(ggplot2)
library(dplyr)
library(knitr)
library(shiny)
library(rmarkdown)
fill_golrazlika <- c(podatki$`Goal Difference` + 50)
Prikaz <- ggplot(data=podatki) + aes(x=Position, y=Points, fill=fill_golrazlika) + geom_smooth()
View(Prikaz)